const API_BASE=window.GLOBALBLOCS_API_BASE||"http://127.0.0.1:8000";
const demo={kpis:{real_gdp_growth:{value:2.8,unit:"%"},inflation:{value:3.1,unit:"%"},unemployment:{value:4.2,unit:"%"},policy_rate:{value:4.25,unit:"%"},trade_balance:{value:-215,unit:"USD billions"}},observations:[{country:"United States",bloc:"North America",variable:"Real GDP Growth",period:"2025",value:2.8,unit:"%"},{country:"United States",bloc:"North America",variable:"Inflation Rate",period:"2025",value:3.1,unit:"%"},{country:"Germany",bloc:"European Union",variable:"Real GDP Growth",period:"2025",value:1.1,unit:"%"},{country:"Japan",bloc:"Asia-Pacific",variable:"Real GDP Growth",period:"2025",value:1.0,unit:"%"},{country:"Brazil",bloc:"Emerging Markets",variable:"Inflation Rate",period:"2025",value:4.8,unit:"%"},{country:"India",bloc:"Emerging Markets",variable:"Real GDP Growth",period:"2025",value:6.4,unit:"%"}]};
let state={overview:demo,observations:demo.observations,dataMode:"demo"};
const venues=[["NYSE","United States","Equities"],["Nasdaq","United States","Equities"],["London Stock Exchange","United Kingdom","Equities"],["Deutsche Börse","Germany","Equities"],["Japan Exchange Group","Japan","Equities/Derivatives"],["Shanghai Stock Exchange","China","Equities"],["Hong Kong Exchanges and Clearing","Hong Kong","Equities/Derivatives"],["National Stock Exchange of India","India","Equities/Derivatives"],["B3","Brazil","Equities/Derivatives"],["Johannesburg Stock Exchange","South Africa","Equities/Derivatives"],["ASX","Australia","Equities/Derivatives"],["Singapore Exchange","Singapore","Equities/Derivatives"]];
const $=id=>document.getElementById(id);
async function get(path){const r=await fetch(API_BASE+path);if(!r.ok)throw Error(r.statusText);return r.json()}
async function load(){try{state.overview=await get("/api/v1/overview");state.dataMode=state.overview.data_mode||"api";state.observations=await get("/api/v1/observations");setStatus("API connected • "+state.dataMode,"good")}catch(e){state.dataMode="demo";setStatus("Offline demo mode • connect FastAPI for repository data","warn")}render()}
function setStatus(text,kind){$("status").textContent=text;$("status").className="status "+kind}
function render(){const k=state.overview.kpis||demo.kpis;[["gdp","real_gdp_growth"],["infl","inflation"],["unemp","unemployment"],["rate","policy_rate"],["trade","trade_balance"]].forEach(([id,key])=>{const x=k[key];$(id).textContent=x.unit==="USD billions"?"$"+x.value+"B":x.value+"%"});const q=($("search").value||"").toLowerCase();$("marketRows").innerHTML=venues.map(v=>"<tr><td>"+v[0]+"</td><td>"+v[1]+"</td><td>"+v[2]+"</td></tr>").join("");$("tradeRows").innerHTML=state.observations.filter(r=>r.variable.includes("Exports")||r.variable.includes("Imports")).map(r=>"<tr><td>"+r.country+"</td><td>Global partners</td><td>"+r.variable+"</td><td>"+r.value+" "+r.unit+"</td></tr>").join("");$("datarows").innerHTML=state.observations.filter(r=>(r.country+" "+r.bloc+" "+r.variable+" "+r.period).toLowerCase().includes(q)).map(r=>"<tr><td>"+r.country+"</td><td>"+r.bloc+"</td><td>"+r.variable+"</td><td>"+r.period+"</td><td>"+r.value+r.unit+"</td></tr>").join("")}
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll("main section").forEach(s=>s.hidden=s.id!==b.dataset.page)});
$("search").oninput=render;
$("reset").onclick=()=>{$("search").value="";document.querySelectorAll("select").forEach(s=>s.selectedIndex=0);render()};
$("export").onclick=()=>{const blob=new Blob([JSON.stringify({data_mode:state.dataMode,filters:{bloc:$("bloc").value,country:$("country").value,indicator:$("indicator").value,period:$("period").value,frequency:$("frequency").value},observations:state.observations},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="globalblocs-dashboard-view.json";a.click();URL.revokeObjectURL(a.href)};
load();