"""Global BLOC macroeconomic and microeconomic concept catalog.

The catalog is intentionally metadata-driven so concepts can be surfaced in the
dashboard, linked to country/region data, and later connected to calculation
engines and ML feature pipelines.
"""

MACRO_CONCEPTS = [
    {"id":1,"name":"Scarcity","category":"Foundations","formula":"Resources < unlimited wants","indicator":None},
    {"id":2,"name":"Opportunity Cost","category":"Foundations","formula":"Value of next-best alternative forgone","indicator":None},
    {"id":3,"name":"Production Possibilities Curve","category":"Foundations","formula":"Maximum feasible output combinations","indicator":None},
    {"id":4,"name":"Absolute Advantage","category":"Trade","formula":"Lower resource cost per unit","indicator":None},
    {"id":5,"name":"Comparative Advantage","category":"Trade","formula":"Lower opportunity cost","indicator":None},
    {"id":6,"name":"Specialization","category":"Trade","formula":"Concentrate production where opportunity cost is lowest","indicator":None},
    {"id":7,"name":"Demand","category":"Markets","formula":"Qd = f(P, income, preferences, substitutes, complements)","indicator":None},
    {"id":8,"name":"Supply","category":"Markets","formula":"Qs = f(P, input costs, technology, taxes)","indicator":None},
    {"id":9,"name":"Market Equilibrium","category":"Markets","formula":"Qd = Qs","indicator":None},
    {"id":10,"name":"Price Ceiling","category":"Policy","formula":"P <= legal maximum","indicator":None},
    {"id":11,"name":"Price Floor","category":"Policy","formula":"P >= legal minimum","indicator":None},
    {"id":12,"name":"Tariff","category":"Trade","formula":"Tax on imports","indicator":None},
    {"id":13,"name":"Circular Flow","category":"National Accounts","formula":"Income = spending = output","indicator":None},
    {"id":14,"name":"GDP","category":"National Accounts","formula":"C + I + G + (X-M)","indicator":"NY.GDP.MKTP.CD"},
    {"id":15,"name":"Real GDP","category":"National Accounts","formula":"Nominal GDP / GDP deflator * 100","indicator":"NY.GDP.MKTP.KD"},
    {"id":16,"name":"Nominal GDP","category":"National Accounts","formula":"Current-price output","indicator":"NY.GDP.MKTP.CD"},
    {"id":17,"name":"GDP Per Capita","category":"National Accounts","formula":"GDP / population","indicator":"NY.GDP.PCAP.CD"},
    {"id":18,"name":"GDP Growth","category":"National Accounts","formula":"(GDP_t/GDP_t-1)-1","indicator":"NY.GDP.MKTP.KD.ZG"},
    {"id":19,"name":"Consumption","category":"National Accounts","formula":"Household spending","indicator":"NE.CON.PRVT.CD"},
    {"id":20,"name":"Investment","category":"National Accounts","formula":"Spending on capital formation","indicator":"NE.GDI.FTOT.CD"},
    {"id":21,"name":"Government Spending","category":"National Accounts","formula":"Public-sector final consumption and investment","indicator":"NE.CON.GOVT.CD"},
    {"id":22,"name":"Net Exports","category":"Trade","formula":"Exports - imports","indicator":"NE.TRD.GNFS.CD"},
    {"id":23,"name":"GDP Deflator","category":"Prices","formula":"Nominal GDP / real GDP * 100","indicator":"NY.GDP.DEFL.KD.ZG"},
    {"id":24,"name":"Inflation","category":"Prices","formula":"Percentage change in general price level","indicator":"FP.CPI.TOTL.ZG"},
    {"id":25,"name":"Consumer Price Index","category":"Prices","formula":"Cost of representative consumption basket","indicator":"FP.CPI.TOTL"},
    {"id":26,"name":"Demand-Pull Inflation","category":"Prices","formula":"Aggregate demand pressure on capacity","indicator":None},
    {"id":27,"name":"Cost-Push Inflation","category":"Prices","formula":"Input-cost shock raising prices","indicator":None},
    {"id":28,"name":"Unemployment Rate","category":"Labor","formula":"Unemployed / labor force","indicator":"SL.UEM.TOTL.ZS"},
    {"id":29,"name":"Labor Force Participation","category":"Labor","formula":"Labor force / working-age population","indicator":"SL.TLF.CACT.ZS"},
    {"id":30,"name":"Natural Rate of Unemployment","category":"Labor","formula":"Structural + frictional unemployment","indicator":None},
    {"id":31,"name":"Frictional Unemployment","category":"Labor","formula":"Temporary job-search unemployment","indicator":None},
    {"id":32,"name":"Structural Unemployment","category":"Labor","formula":"Skill/location mismatch","indicator":None},
    {"id":33,"name":"Cyclical Unemployment","category":"Labor","formula":"Demand-cycle unemployment","indicator":None},
    {"id":34,"name":"Aggregate Demand","category":"AD-AS","formula":"AD = C + I + G + NX","indicator":None},
    {"id":35,"name":"AD Multiplier","category":"AD-AS","formula":"1/(1-MPC) in simple model","indicator":None},
    {"id":36,"name":"Crowding Out","category":"Policy","formula":"Public borrowing reducing private spending","indicator":None},
    {"id":37,"name":"Short-Run Aggregate Supply","category":"AD-AS","formula":"Output supplied at sticky prices/wages","indicator":None},
    {"id":38,"name":"Long-Run Aggregate Supply","category":"AD-AS","formula":"Potential output at flexible prices","indicator":None},
    {"id":39,"name":"Potential GDP","category":"Growth","formula":"Sustainable full-employment output","indicator":"NY.GDP.MKTP.KD"},
    {"id":40,"name":"Output Gap","category":"Business Cycle","formula":"(Actual GDP - Potential GDP)/Potential GDP","indicator":None},
    {"id":41,"name":"Business Cycle","category":"Business Cycle","formula":"Expansion, peak, contraction, trough","indicator":None},
    {"id":42,"name":"Economic Recession","category":"Business Cycle","formula":"Sustained broad decline in activity","indicator":None},
    {"id":43,"name":"Money Supply","category":"Money","formula":"Stock of money/liquid deposits","indicator":None},
    {"id":44,"name":"Money Demand","category":"Money","formula":"Desired real money balances","indicator":None},
    {"id":45,"name":"Money Multiplier","category":"Money","formula":"1 / reserve ratio in simple model","indicator":None},
    {"id":46,"name":"Quantity Theory of Money","category":"Money","formula":"MV = PY","indicator":None},
    {"id":47,"name":"Real Interest Rate","category":"Interest Rates","formula":"Nominal rate - expected inflation","indicator":None},
    {"id":48,"name":"Nominal Interest Rate","category":"Interest Rates","formula":"Stated market interest rate","indicator":None},
    {"id":49,"name":"Loanable Funds","category":"Financial Sector","formula":"Savings and investment determine real rate","indicator":None},
    {"id":50,"name":"Time Value of Money","category":"Financial Sector","formula":"PV = FV/(1+r)^n","indicator":None},
    {"id":51,"name":"Fiscal Policy","category":"Stabilization","formula":"Taxes + government spending","indicator":None},
    {"id":52,"name":"Monetary Policy","category":"Stabilization","formula":"Central-bank policy affecting financial conditions","indicator":None},
    {"id":53,"name":"Fiscal Multiplier","category":"Stabilization","formula":"Delta Y / Delta G","indicator":None},
    {"id":54,"name":"Government Budget Balance","category":"Fiscal","formula":"Revenue - expenditure","indicator":None},
    {"id":55,"name":"Government Deficit","category":"Fiscal","formula":"Expenditure - revenue","indicator":None},
    {"id":56,"name":"Public Debt","category":"Fiscal","formula":"Accumulated government borrowing","indicator":"GC.DOD.TOTL.GD.ZS"},
    {"id":57,"name":"Debt-to-GDP","category":"Fiscal","formula":"Public debt / GDP","indicator":"GC.DOD.TOTL.GD.ZS"},
    {"id":58,"name":"Phillips Curve","category":"Stabilization","formula":"Inflation-unemployment relationship","indicator":None},
    {"id":59,"name":"Expected Inflation","category":"Prices","formula":"Expected future price growth","indicator":None},
    {"id":60,"name":"Economic Growth","category":"Growth","formula":"Sustained increase in real output","indicator":"NY.GDP.MKTP.KD.ZG"},
    {"id":61,"name":"GDP Per Worker","category":"Productivity","formula":"Real output / employment","indicator":None},
    {"id":62,"name":"Labor Productivity","category":"Productivity","formula":"Output / labor input","indicator":"SL.GDP.PCAP.EM.KD"},
    {"id":63,"name":"Human Capital","category":"Growth","formula":"Skills and knowledge embodied in labor","indicator":None},
    {"id":64,"name":"Physical Capital","category":"Growth","formula":"Produced capital used in production","indicator":None},
    {"id":65,"name":"Research and Development","category":"Growth","formula":"Resources devoted to innovation","indicator":"GB.XPD.RSDV.GD.ZS"},
    {"id":66,"name":"Total Factor Productivity","category":"Productivity","formula":"Output not explained by measured inputs","indicator":None},
    {"id":67,"name":"Capital Deepening","category":"Productivity","formula":"Capital per worker growth","indicator":None},
    {"id":68,"name":"Balance of Trade","category":"Open Economy","formula":"Exports - imports of goods/services","indicator":"NE.TRD.GNFS.CD"},
    {"id":69,"name":"Current Account","category":"Open Economy","formula":"Trade + income + transfers","indicator":"BN.CAB.XOKA.GD.ZS"},
    {"id":70,"name":"Financial Account","category":"Open Economy","formula":"Cross-border financial flows","indicator":None},
    {"id":71,"name":"Capital Account","category":"Open Economy","formula":"Capital transfers and non-produced assets","indicator":None},
    {"id":72,"name":"Balance of Payments","category":"Open Economy","formula":"Current + capital + financial balances","indicator":None},
    {"id":73,"name":"Exchange Rate","category":"FX","formula":"Price of one currency in another","indicator":"PA.NUS.FCRF"},
    {"id":74,"name":"Currency Appreciation","category":"FX","formula":"Rise in currency value","indicator":None},
    {"id":75,"name":"Currency Depreciation","category":"FX","formula":"Fall in currency value","indicator":None},
    {"id":76,"name":"Purchasing Power Parity","category":"FX","formula":"Comparable price levels across currencies","indicator":None},
    {"id":77,"name":"Real Exchange Rate","category":"FX","formula":"Nominal FX adjusted for relative prices","indicator":None},
    {"id":78,"name":"Foreign Exchange Demand","category":"FX","formula":"Demand for a currency","indicator":None},
    {"id":79,"name":"Foreign Exchange Supply","category":"FX","formula":"Supply of a currency","indicator":None},
    {"id":80,"name":"Capital Inflow","category":"Capital Flows","formula":"Foreign capital entering an economy","indicator":"BX.KLT.DINV.CD.WD"},
    {"id":81,"name":"Capital Outflow","category":"Capital Flows","formula":"Domestic capital invested abroad","indicator":None},
    {"id":82,"name":"Foreign Direct Investment","category":"Capital Flows","formula":"Cross-border investment with lasting interest","indicator":"BX.KLT.DINV.CD.WD"},
    {"id":83,"name":"Portfolio Investment","category":"Capital Flows","formula":"Cross-border investment in securities","indicator":None},
    {"id":84,"name":"Trade Openness","category":"Trade","formula":"(Exports + imports)/GDP","indicator":"NE.TRD.GNFS.ZS"},
    {"id":85,"name":"Terms of Trade","category":"Trade","formula":"Export prices / import prices","indicator":None},
    {"id":86,"name":"Tariff Rate","category":"Trade","formula":"Import duty / import value","indicator":None},
    {"id":87,"name":"Central Bank Balance Sheet","category":"Monetary Policy","formula":"Assets and liabilities of central bank","indicator":None},
    {"id":88,"name":"Policy Rate","category":"Monetary Policy","formula":"Central-bank administered short-term rate","indicator":None},
    {"id":89,"name":"Reserve Requirement","category":"Monetary Policy","formula":"Required reserves / eligible deposits","indicator":None},
    {"id":90,"name":"Quantitative Easing","category":"Monetary Policy","formula":"Large-scale asset purchases","indicator":None},
    {"id":91,"name":"Yield Curve","category":"Financial Sector","formula":"Interest rates across maturities","indicator":None},
    {"id":92,"name":"Yield Curve Spread","category":"Financial Sector","formula":"Long rate - short rate","indicator":None},
    {"id":93,"name":"Financial Conditions","category":"Financial Sector","formula":"Composite cost/availability of finance","indicator":None},
    {"id":94,"name":"Credit Growth","category":"Banking","formula":"Change in credit outstanding","indicator":None},
    {"id":95,"name":"Bank Credit to Private Sector","category":"Banking","formula":"Bank claims on private sector","indicator":"FS.AST.PRVT.GD.ZS"},
    {"id":96,"name":"Financial Inclusion","category":"Banking","formula":"Access and use of financial services","indicator":None},
    {"id":97,"name":"Systemic Risk","category":"Risk","formula":"Risk of broad financial-system disruption","indicator":None},
    {"id":98,"name":"Sovereign Risk","category":"Risk","formula":"Risk associated with government creditworthiness","indicator":None},
    {"id":99,"name":"Economic Resilience","category":"Risk","formula":"Capacity to absorb and recover from shocks","indicator":None},
    {"id":100,"name":"Macroeconomic Stability","category":"Risk","formula":"Joint stability of growth, prices, labor, fiscal and external balances","indicator":None},
]

MICRO_CONCEPTS = [
    {"id":1,"name":"Scarcity","category":"Foundations","formula":"Resources < unlimited wants"},
    {"id":2,"name":"Choice","category":"Foundations","formula":"Selection among alternatives"},
    {"id":3,"name":"Opportunity Cost","category":"Foundations","formula":"Next-best alternative forgone"},
    {"id":4,"name":"Marginal Analysis","category":"Foundations","formula":"Compare marginal benefit and marginal cost"},
    {"id":5,"name":"Incentives","category":"Institutions","formula":"Benefits/costs that alter behavior"},
    {"id":6,"name":"Property Rights","category":"Institutions","formula":"Legal control over resource use"},
    {"id":7,"name":"Economic Systems","category":"Institutions","formula":"Rules for organizing production and allocation"},
    {"id":8,"name":"Demand","category":"Product Markets","formula":"Qd = f(P, income, preferences)"},
    {"id":9,"name":"Supply","category":"Product Markets","formula":"Qs = f(P, costs, technology)"},
    {"id":10,"name":"Equilibrium Price","category":"Product Markets","formula":"Price where Qd = Qs"},
    {"id":11,"name":"Equilibrium Quantity","category":"Product Markets","formula":"Quantity where Qd = Qs"},
    {"id":12,"name":"Demand Determinants","category":"Product Markets","formula":"Income, tastes, expectations, related goods, buyers"},
    {"id":13,"name":"Supply Determinants","category":"Product Markets","formula":"Input costs, technology, taxes, expectations, sellers"},
    {"id":14,"name":"Price Ceiling","category":"Policy","formula":"Legal maximum price"},
    {"id":15,"name":"Price Floor","category":"Policy","formula":"Legal minimum price"},
    {"id":16,"name":"Price Elasticity of Demand","category":"Elasticity","formula":"%Delta Qd / %Delta P"},
    {"id":17,"name":"Price Elasticity of Supply","category":"Elasticity","formula":"%Delta Qs / %Delta P"},
    {"id":18,"name":"Income Elasticity","category":"Elasticity","formula":"%Delta Q / %Delta income"},
    {"id":19,"name":"Cross-Price Elasticity","category":"Elasticity","formula":"%Delta Qx / %Delta Py"},
    {"id":20,"name":"Total Revenue Test","category":"Elasticity","formula":"TR = P * Q"},
    {"id":21,"name":"Consumer Surplus","category":"Welfare","formula":"Willingness to pay - price paid"},
    {"id":22,"name":"Producer Surplus","category":"Welfare","formula":"Price received - willingness to sell"},
    {"id":23,"name":"Total Surplus","category":"Welfare","formula":"Consumer surplus + producer surplus"},
    {"id":24,"name":"Deadweight Loss","category":"Welfare","formula":"Lost gains from trade"},
    {"id":25,"name":"Tax Incidence","category":"Policy","formula":"Distribution of tax burden between buyers and sellers"},
    {"id":26,"name":"Marginal Utility","category":"Consumer Choice","formula":"Delta TU / Delta Q"},
    {"id":27,"name":"Total Utility","category":"Consumer Choice","formula":"Sum of utility from consumption"},
    {"id":28,"name":"Utility Maximization","category":"Consumer Choice","formula":"MUx/Px = MUy/Py"},
    {"id":29,"name":"Income Effect","category":"Consumer Choice","formula":"Consumption change from purchasing-power change"},
    {"id":30,"name":"Substitution Effect","category":"Consumer Choice","formula":"Consumption change from relative-price change"},
    {"id":31,"name":"Normal Good","category":"Consumer Choice","formula":"Demand rises with income"},
    {"id":32,"name":"Inferior Good","category":"Consumer Choice","formula":"Demand falls with income"},
    {"id":33,"name":"Substitute Goods","category":"Consumer Choice","formula":"Goods with positive cross-price effect"},
    {"id":34,"name":"Complementary Goods","category":"Consumer Choice","formula":"Goods with negative cross-price effect"},
    {"id":35,"name":"Production Function","category":"Production","formula":"Q = f(L,K,technology)"},
    {"id":36,"name":"Total Product","category":"Production","formula":"Total output"},
    {"id":37,"name":"Marginal Product of Labor","category":"Production","formula":"Delta Q / Delta L"},
    {"id":38,"name":"Marginal Product of Capital","category":"Production","formula":"Delta Q / Delta K"},
    {"id":39,"name":"Average Product of Labor","category":"Production","formula":"Q / L"},
    {"id":40,"name":"Diminishing Marginal Returns","category":"Production","formula":"Marginal product eventually falls as one input rises"},
    {"id":41,"name":"Fixed Cost","category":"Costs","formula":"Cost independent of short-run output"},
    {"id":42,"name":"Variable Cost","category":"Costs","formula":"Cost that changes with output"},
    {"id":43,"name":"Total Cost","category":"Costs","formula":"TC = FC + VC"},
    {"id":44,"name":"Average Fixed Cost","category":"Costs","formula":"AFC = FC/Q"},
    {"id":45,"name":"Average Variable Cost","category":"Costs","formula":"AVC = VC/Q"},
    {"id":46,"name":"Average Total Cost","category":"Costs","formula":"ATC = TC/Q"},
    {"id":47,"name":"Marginal Cost","category":"Costs","formula":"MC = Delta TC / Delta Q"},
    {"id":48,"name":"Economies of Scale","category":"Costs","formula":"Long-run average cost falls as scale rises"},
    {"id":49,"name":"Diseconomies of Scale","category":"Costs","formula":"Long-run average cost rises as scale rises"},
    {"id":50,"name":"Minimum Efficient Scale","category":"Costs","formula":"Smallest output at minimum LRAC"},
    {"id":51,"name":"Accounting Profit","category":"Firm Behavior","formula":"Revenue - explicit costs"},
    {"id":52,"name":"Economic Profit","category":"Firm Behavior","formula":"Revenue - explicit - implicit costs"},
    {"id":53,"name":"Normal Profit","category":"Firm Behavior","formula":"Economic profit = 0"},
    {"id":54,"name":"Marginal Revenue","category":"Firm Behavior","formula":"Delta TR / Delta Q"},
    {"id":55,"name":"Profit Maximization","category":"Firm Behavior","formula":"MR = MC"},
    {"id":56,"name":"Perfect Competition","category":"Market Structure","formula":"Many firms; price takers; homogeneous product"},
    {"id":57,"name":"Competitive Firm Supply","category":"Market Structure","formula":"MC above AVC in short run"},
    {"id":58,"name":"Shutdown Point","category":"Market Structure","formula":"P < minimum AVC"},
    {"id":59,"name":"Long-Run Competitive Equilibrium","category":"Market Structure","formula":"P = MC = minimum ATC"},
    {"id":60,"name":"Allocative Efficiency","category":"Efficiency","formula":"P = MC"},
    {"id":61,"name":"Productive Efficiency","category":"Efficiency","formula":"Output at minimum ATC"},
    {"id":62,"name":"Monopoly","category":"Market Structure","formula":"Single dominant seller with entry barriers"},
    {"id":63,"name":"Market Power","category":"Market Structure","formula":"Ability to influence price"},
    {"id":64,"name":"Barriers to Entry","category":"Market Structure","formula":"Conditions limiting new competitors"},
    {"id":65,"name":"Monopoly Price Discrimination","category":"Market Structure","formula":"Different prices for different buyer groups"},
    {"id":66,"name":"Natural Monopoly","category":"Market Structure","formula":"One firm has lower cost over relevant output range"},
    {"id":67,"name":"Oligopoly","category":"Market Structure","formula":"Few interdependent firms"},
    {"id":68,"name":"Strategic Interdependence","category":"Game Theory","formula":"Best action depends on rivals' actions"},
    {"id":69,"name":"Payoff Matrix","category":"Game Theory","formula":"Payoffs for strategy combinations"},
    {"id":70,"name":"Nash Equilibrium","category":"Game Theory","formula":"No player gains by unilateral deviation"},
    {"id":71,"name":"Prisoner's Dilemma","category":"Game Theory","formula":"Individual incentives can produce inefficient equilibrium"},
    {"id":72,"name":"Collusion","category":"Game Theory","formula":"Coordinated behavior among competitors"},
    {"id":73,"name":"Cartel","category":"Game Theory","formula":"Formal agreement among sellers to restrict competition"},
    {"id":74,"name":"Monopolistic Competition","category":"Market Structure","formula":"Many firms with differentiated products"},
    {"id":75,"name":"Product Differentiation","category":"Market Structure","formula":"Perceived differences across competing products"},
    {"id":76,"name":"Excess Capacity","category":"Market Structure","formula":"Output below minimum ATC in long-run differentiated competition"},
    {"id":77,"name":"Derived Demand","category":"Factor Markets","formula":"Factor demand derived from product demand"},
    {"id":78,"name":"Marginal Revenue Product","category":"Factor Markets","formula":"MRP = MP * MR"},
    {"id":79,"name":"Value of Marginal Product","category":"Factor Markets","formula":"VMP = MP * product price"},
    {"id":80,"name":"Labor Demand","category":"Factor Markets","formula":"Hire labor where MRP = wage"},
    {"id":81,"name":"Labor Supply","category":"Factor Markets","formula":"Labor supplied as a function of wage and alternatives"},
    {"id":82,"name":"Wage Determination","category":"Factor Markets","formula":"Labor demand intersects labor supply"},
    {"id":83,"name":"Economic Rent","category":"Factor Markets","formula":"Payment above transfer earnings"},
    {"id":84,"name":"Externality","category":"Market Failure","formula":"Third-party cost or benefit"},
    {"id":85,"name":"Marginal Social Cost","category":"Market Failure","formula":"MPC + marginal external cost"},
    {"id":86,"name":"Marginal Social Benefit","category":"Market Failure","formula":"MPB + marginal external benefit"},
    {"id":87,"name":"Pigouvian Tax","category":"Policy","formula":"Tax equal to marginal external cost"},
    {"id":88,"name":"Pigouvian Subsidy","category":"Policy","formula":"Subsidy equal to marginal external benefit"},
    {"id":89,"name":"Tradable Permits","category":"Policy","formula":"Market for transferable emissions rights"},
    {"id":90,"name":"Public Good","category":"Public Goods","formula":"Nonrival and nonexcludable"},
    {"id":91,"name":"Private Good","category":"Public Goods","formula":"Rival and excludable"},
    {"id":92,"name":"Free-Rider Problem","category":"Public Goods","formula":"Benefit without paying"},
    {"id":93,"name":"Common Resource","category":"Public Goods","formula":"Rival but difficult to exclude"},
    {"id":94,"name":"Tragedy of the Commons","category":"Public Goods","formula":"Overuse of common resources"},
    {"id":95,"name":"Antitrust","category":"Competition Policy","formula":"Policy to preserve competition"},
    {"id":96,"name":"Regulation","category":"Competition Policy","formula":"Government rules affecting market behavior"},
    {"id":97,"name":"Lorenz Curve","category":"Income Distribution","formula":"Cumulative income share vs cumulative population share"},
    {"id":98,"name":"Gini Coefficient","category":"Income Distribution","formula":"0 = perfect equality; 1 = maximum inequality"},
    {"id":99,"name":"Income Inequality","category":"Income Distribution","formula":"Unequal distribution of income"},
    {"id":100,"name":"Market Efficiency","category":"Efficiency","formula":"Maximum feasible total surplus subject to constraints"},
]

MACRO_BY_ID = {x["id"]: x for x in MACRO_CONCEPTS}
MICRO_BY_ID = {x["id"]: x for x in MICRO_CONCEPTS}
