"""GlobalBLOCS 350-Metric Knowledge Base.

Exactly 100 return/performance, 100 portfolio/risk, 50 risk-adjusted, and 100 quantitative-finance records. Visualization recommendations are advisory; all compatible chart types remain selectable.
"""
from __future__ import annotations
from typing import Any

CATEGORY_COUNTS = {"return_performance":100,"portfolio_risk":100,"risk_adjusted":50,"quantitative_finance":100}
METRIC_GROUPS = {
  "return_performance": [
    "Total Return",
    "Annualized Return (CAGR)",
    "Absolute Return",
    "Holding Period Return",
    "Expected Return",
    "Excess Return",
    "Real Return",
    "Risk-Adjusted Return",
    "Dividend Yield",
    "Capital Gain Yield",
    "Price Return",
    "Dividend Return",
    "Log Return",
    "Simple Return",
    "Geometric Mean Return",
    "Arithmetic Mean Return",
    "Median Return",
    "Rolling Return",
    "Compounded Return",
    "Monthly Return",
    "Quarterly Return",
    "YTD Return",
    "Benchmark Relative Return",
    "Active Return",
    "Relative Performance",
    "Gross Return",
    "Net Return",
    "Pre-Tax Return",
    "After-Tax Return",
    "Realized Return",
    "Unrealized Return",
    "Total Shareholder Return",
    "Cash Yield",
    "Earnings Yield",
    "Free Cash Flow Yield",
    "Buyback Yield",
    "Shareholder Yield",
    "Revenue Growth",
    "Earnings Growth",
    "EPS Growth",
    "EBITDA Growth",
    "Operating Income Growth",
    "Net Income Growth",
    "Free Cash Flow Growth",
    "Book Value Growth",
    "Asset Growth",
    "Equity Growth",
    "Dividend Growth",
    "Cash Flow Growth",
    "Margin Expansion",
    "Gross Margin",
    "Operating Margin",
    "EBIT Margin",
    "EBITDA Margin",
    "Net Profit Margin",
    "FCF Margin",
    "ROA",
    "ROE",
    "ROIC",
    "ROCE",
    "RONA",
    "Asset Turnover",
    "Equity Multiplier",
    "DuPont ROE",
    "Revenue per Share",
    "Earnings per Share",
    "Book Value per Share",
    "Cash Flow per Share",
    "Free Cash Flow per Share",
    "Dividend per Share",
    "Economic Value Added (EVA)",
    "Market Value Added (MVA)",
    "Economic Profit",
    "Residual Income",
    "Revenue CAGR",
    "EPS CAGR",
    "FCF CAGR",
    "EBITDA CAGR",
    "Operating Income CAGR",
    "Net Income CAGR",
    "Dividend CAGR",
    "Book Value CAGR",
    "Cash Flow CAGR",
    "Invested Capital Growth",
    "Operating Leverage",
    "Financial Leverage",
    "Combined Leverage",
    "Revenue Retention Rate",
    "Customer Growth Rate",
    "Market Share Growth",
    "Productivity Growth",
    "Capital Productivity",
    "Labor Productivity Growth",
    "Total Factor Productivity Growth",
    "Daily Total Return",
    "Daily Annualized Return (CAGR)",
    "Daily Absolute Return",
    "Daily Holding Period Return",
    "Daily Expected Return",
    "Daily Excess Return"
  ],
  "portfolio_risk": [
    "Standard Deviation",
    "Variance",
    "Beta",
    "Alpha",
    "Maximum Drawdown",
    "Downside Deviation",
    "Value at Risk (VaR)",
    "Conditional Value at Risk (CVaR)",
    "Tracking Error",
    "Volatility",
    "Historical Volatility",
    "Realized Volatility",
    "Implied Volatility",
    "Downside Volatility",
    "Upside Volatility",
    "Semi-Deviation",
    "Range Volatility",
    "Parkinson Volatility",
    "Garman-Klass Volatility",
    "Rogers-Satchell Volatility",
    "Yang-Zhang Volatility",
    "Average True Range",
    "Maximum Drawup",
    "Drawdown Duration",
    "Recovery Time",
    "Ulcer Index",
    "Pain Index",
    "Pain Ratio",
    "Calmar Ratio",
    "Sterling Ratio",
    "Burke Ratio",
    "Martin Ratio",
    "Tail Loss",
    "Expected Shortfall",
    "VaR Breach Rate",
    "VaR Backtest Count",
    "Skewness",
    "Kurtosis",
    "Tail Index",
    "Extreme Loss Frequency",
    "Correlation Coefficient",
    "Covariance",
    "Downside Correlation",
    "Beta to Market",
    "Beta to Sector",
    "Beta to Factor",
    "Rolling Beta",
    "Rolling Correlation",
    "Correlation Stability",
    "Diversification Ratio",
    "Portfolio Variance",
    "Portfolio Standard Deviation",
    "Portfolio Beta",
    "Portfolio Expected Return",
    "Portfolio Sharpe Ratio",
    "Portfolio Concentration Ratio",
    "Portfolio Turnover",
    "Asset Allocation",
    "Marginal Risk Contribution",
    "Component Risk Contribution",
    "Risk Contribution Percentage",
    "Risk Budget Utilization",
    "Herfindahl-Hirschman Concentration",
    "Effective Number of Holdings",
    "Number of Holdings",
    "Largest Position Weight",
    "Top-5 Concentration",
    "Top-10 Concentration",
    "Sector Concentration",
    "Country Concentration",
    "Factor Concentration",
    "Liquidity Risk",
    "Bid-Ask Spread",
    "Market Impact",
    "Amihud Illiquidity",
    "Turnover Ratio",
    "Dollar Volume",
    "Average Daily Volume",
    "Volume Volatility",
    "Open Interest",
    "Leverage Ratio",
    "Debt-to-Equity",
    "Debt-to-Assets",
    "Net Debt-to-EBITDA",
    "Interest Coverage",
    "Fixed Charge Coverage",
    "Current Ratio",
    "Quick Ratio",
    "Cash Ratio",
    "Altman Z-Score",
    "Distance to Default",
    "Probability of Default",
    "Loss Given Default",
    "Expected Loss",
    "Credit VaR",
    "Spread Duration",
    "Credit Spread",
    "Spread Volatility",
    "Duration",
    "Convexity"
  ],
  "risk_adjusted": [
    "Sharpe Ratio",
    "Sortino Ratio",
    "Treynor Ratio",
    "Information Ratio",
    "Omega Ratio",
    "Jensen's Alpha",
    "Appraisal Ratio",
    "M² Measure",
    "R-Squared",
    "Upside Capture Ratio",
    "Downside Capture Ratio",
    "Capture Ratio",
    "Gain-Loss Ratio",
    "Profit Factor",
    "Sterling Risk Ratio",
    "Burke Risk Ratio",
    "Martin Risk Ratio",
    "Treynor-Black Ratio",
    "Modigliani-Modigliani Measure",
    "Active Return / Active Risk",
    "Return on VaR",
    "Return on CVaR",
    "Return on Maximum Drawdown",
    "Return on Ulcer Index",
    "Return on Downside Deviation",
    "Return on Semi-Deviation",
    "Return on Tail Risk",
    "Risk-Adjusted Alpha",
    "Risk-Adjusted Beta",
    "Alpha-to-Volatility",
    "Alpha-to-Drawdown",
    "Information Coefficient",
    "Rank Information Coefficient",
    "IC Information Ratio",
    "Factor Information Ratio",
    "Hit Ratio",
    "Directional Accuracy",
    "Win Rate",
    "Loss Rate",
    "Payoff Ratio",
    "Expectancy",
    "Profitability Ratio",
    "Reward-to-Risk Ratio",
    "Gain-to-Pain Ratio",
    "Recovery Factor",
    "Risk Efficiency Ratio",
    "Diversification Benefit",
    "Marginal Sharpe Contribution",
    "Omega Ratio Adjusted",
    "Rolling Sharpe Ratio"
  ],
  "quantitative_finance": [
    "P/E",
    "Forward P/E",
    "P/B",
    "P/S",
    "P/CF",
    "Enterprise Value",
    "EV/EBITDA",
    "PEG Ratio",
    "Dividend Payout Ratio",
    "FCF Yield",
    "EV/Revenue",
    "EV/EBIT",
    "EV/FCF",
    "Price/FCF",
    "Price/Book Growth",
    "Price/Sales Growth",
    "Forward Earnings Yield",
    "Enterprise Yield",
    "Free Cash Flow Conversion",
    "Cash Conversion Ratio",
    "Cash Flow Coverage",
    "Working Capital",
    "Net Working Capital",
    "Working Capital Turnover",
    "Inventory Turnover",
    "Receivables Turnover",
    "Payables Turnover",
    "Days Sales Outstanding",
    "Days Inventory Outstanding",
    "Days Payable Outstanding",
    "Cash Conversion Cycle",
    "Gross Profit Growth",
    "Cost of Revenue Growth",
    "SG&A Growth",
    "R&D Growth",
    "CapEx Growth",
    "Depreciation Growth",
    "Tax Rate",
    "Effective Tax Rate",
    "EBITDA",
    "EBIT",
    "NOPAT",
    "Operating Cash Flow",
    "Capital Expenditures",
    "Free Cash Flow",
    "Free Cash Flow to Debt",
    "Operating Cash Flow to Debt",
    "Debt Service Coverage",
    "Interest Expense",
    "Interest Coverage Ratio",
    "Net Debt",
    "Gross Debt",
    "Cash and Equivalents",
    "Cash-to-Debt",
    "Debt Maturity Profile",
    "Debt Duration",
    "Debt Refinancing Risk",
    "Lease Liability",
    "Market Capitalization",
    "Enterprise Value / Market Cap",
    "Float-Adjusted Market Cap",
    "Shares Outstanding",
    "Shares Float",
    "Short Interest",
    "Short Interest Ratio",
    "Days to Cover",
    "Institutional Ownership",
    "Insider Ownership",
    "Insider Buying Ratio",
    "Institutional Flow",
    "Fund Flow",
    "ETF Flow",
    "Mutual Fund Flow",
    "Foreign Investor Flow",
    "Price Momentum",
    "RSI",
    "MACD",
    "Rate of Change",
    "Stochastic Oscillator",
    "ADX",
    "CCI",
    "MFI",
    "On-Balance Volume",
    "Accumulation/Distribution",
    "Bollinger Band Width",
    "Bollinger %B",
    "Moving Average Spread",
    "Price Distance from 52-Week High",
    "Price Distance from 52-Week Low",
    "Put/Call Ratio",
    "Option Volume",
    "Option Open Interest",
    "Implied Volatility Skew",
    "Volatility Risk Premium",
    "Delta",
    "Gamma",
    "Theta",
    "Vega",
    "Yield to Maturity",
    "Option-Adjusted Spread"
  ]
}
FORMULAS = {
  "Total Return": "(Ending Value / Beginning Value) - 1",
  "Annualized Return (CAGR)": "(Ending / Beginning)^(1/years) - 1",
  "ROA": "Net Income / Average Total Assets",
  "ROE": "Net Income / Average Equity",
  "ROIC": "NOPAT / Invested Capital",
  "Gross Margin": "Gross Profit / Revenue",
  "Operating Margin": "Operating Income / Revenue",
  "Net Profit Margin": "Net Income / Revenue",
  "Dividend Yield": "Annual Dividend / Price",
  "Standard Deviation": "sqrt(Variance(Returns))",
  "Variance": "Var(Returns)",
  "Beta": "Cov(Security, Benchmark) / Var(Benchmark)",
  "Maximum Drawdown": "min(Price / Running Peak - 1)",
  "Value at Risk (VaR)": "Quantile(Returns, 1-Confidence)",
  "Conditional Value at Risk (CVaR)": "Mean(Returns <= VaR)",
  "Sharpe Ratio": "(Annualized Return - Risk-Free Rate) / Annualized Volatility",
  "Sortino Ratio": "(Annualized Return - Risk-Free Rate) / Downside Deviation",
  "P/E": "Price / EPS",
  "P/B": "Price / Book Value per Share",
  "P/S": "Market Capitalization / Revenue",
  "EV/EBITDA": "Enterprise Value / EBITDA",
  "FCF Yield": "Free Cash Flow / Market Capitalization",
  "Current Ratio": "Current Assets / Current Liabilities",
  "Debt-to-Equity": "Total Debt / Equity",
  "Cash Conversion Cycle": "DSO + DIO - DPO",
  "Market Capitalization": "Price × Shares Outstanding",
  "Free Cash Flow": "Operating Cash Flow - Capital Expenditures",
  "RSI": "100 - 100/(1+Average Gain/Average Loss)"
}
ALL_VISUALIZATIONS = ["line","area","bar","stacked_bar","histogram","box","violin","scatter","bubble","heatmap","correlation_matrix","density","ecdf","qq","waterfall","radar","candlestick","ohlc","drawdown","volatility_cone","acf","pacf","roc","precision_recall","confusion_matrix","learning_curve","actual_predicted","forecast_interval","pca_projection","cluster","dendrogram","feature_importance","shap","residual"]

def _recommended(name: str, category: str) -> list[str]:
    n=name.lower()
    if "correlation" in n or "covariance" in n: return ["heatmap","scatter","correlation_matrix"]
    if "drawdown" in n: return ["drawdown","line","area"]
    if "volatility" in n or "var" in n or "risk" in n: return ["line","histogram","box","heatmap"]
    if "revenue" in n or "earnings" in n or "growth" in n or "margin" in n: return ["line","bar","area","waterfall"]
    if "price" in n or "momentum" in n: return ["line","candlestick","volume","histogram"]
    families={"return_performance":["line","bar","area","histogram","box"],"portfolio_risk":["line","drawdown","histogram","heatmap","risk_contribution"],"risk_adjusted":["line","bar","scatter","histogram","radar"],"quantitative_finance":["line","bar","area","scatter","heatmap"]}
    return families[category]

def build_metric(metric_id: int, name: str, category: str) -> dict[str, Any]:
    rec=_recommended(name,category)
    return {"id":metric_id,"name":name,"category":category,"definition":f"{name} is a {category.replace('_',' ')} financial measure.","purpose":f"Supports analysis, comparison, research, reporting, and feature engineering for {name}.","formula":FORMULAS.get(name,f"Metric-specific formula for {name}; see metric implementation documentation."),"variables":["market_prices","financial_statements","portfolio_holdings","macro_series"],"python":f"globalblocs.metrics.metric_{metric_id:03d}","r":f"globalblocsR::metric_{metric_id:03d}()","sql":f"globalblocs.metric_{metric_id:03d}","data_sources":["SEC EDGAR","yfinance","macro/regulatory providers"],"validation":["SEC comparison","yfinance comparison","data quality","provenance"],"visualization":{"default":rec[0],"recommended":[{"type":x,"reason":f"Useful for analyzing {name}."} for x in rec],"available":ALL_VISUALIZATIONS},"statistics":["descriptive statistics","confidence intervals","applicable hypothesis tests"],"ml":{"feature_eligible":True,"point_in_time_required":True,"feature_importance":True,"shap":True},"forecasting":{"lstm":True,"transformer":True,"time_aware_validation":True},"limitations":"Requires compatible source data, aligned frequency, point-in-time controls, and domain-specific interpretation."}

METRIC_KNOWLEDGE_BASE=[]
_i=1
for _category,_names in METRIC_GROUPS.items():
    for _name in _names:
        METRIC_KNOWLEDGE_BASE.append(build_metric(_i,_name,_category)); _i += 1

def metric_catalog(): return METRIC_KNOWLEDGE_BASE.copy()
def get_metric(metric_id: int): return METRIC_KNOWLEDGE_BASE[metric_id-1] if 1 <= metric_id <= len(METRIC_KNOWLEDGE_BASE) else None
def search_metrics(query: str="", category: str|None=None):
    q=(query or "").lower()
    return [m for m in METRIC_KNOWLEDGE_BASE if (not category or m["category"]==category) and (not q or q in (m["name"]+" "+m["category"]).lower())]
def category_summary(): return {k:sum(m["category"]==k for m in METRIC_KNOWLEDGE_BASE) for k in CATEGORY_COUNTS}
def validate_catalog():
    names=[m["name"] for m in METRIC_KNOWLEDGE_BASE]
    return {"count":len(names),"unique":len(set(names)),"categories":category_summary(),"valid":len(names)==350 and len(set(names))==350 and category_summary()==CATEGORY_COUNTS}
